### ISSUE TITLE
Place not loading up

### ISSUE THREAD

**Issue by DoctorPurpleSwag** [Roblox/future-is-bright#14]
When the studio opens up its fine but when i try to enter a place or even make a new baseplate the place window becomes completely white while the start page is fine. It doesn't crash just white screen on the game window.

I have windows 10, i5 core and a GTX 750 ti.

**Comment by LouieK22** [comment]
Duplicated issue, see #4

**Comment by zeux** [comment]
Would you mind:

1) Running prototype Studio build to trigger the issue
2) Going to C:\Users\username\AppData\Local\Roblox\logs
3) Uploading the latest file with _1.txt suffix here?

**Comment by TlPOU** [comment]
I have the same problem as him. But i've did what you've asked, or at least, I think.


_0.14003 0fdc: CrashReporter Start
0.14103 1d28: WatcherThread Started
0.14603 0fdc: Initializing CrashEvent request, url: https://data.roblox.com/Error/Dmp.ashx?filename=C%3A%5CUsers%5Canna%5CAppData%5CLocal%5CRoblox%5Clogs%5Clog%5F00DC7%200%2C%20298%2C%201%2C%20136360%2ERobloxStudio%2Ecrashevent
0.14603 0fdc: Info: RobloxMainWindow::RobloxMainWindow - start
0.40805 0fdc: StudioABTests using browserTrackerId 9432088146
6.80536 0fdc: setAssetFolder C:/Users/anna/AppData/Local/Roblox/Versions/version-64ead513c100423c/content
16.37708 0fdc: Info: RobloxMainWindow::createAndShowIDEDocFromScript https://assetgame.roblox.com/game/edit.ashx?placeId=908690723&upload=908690723&universeId=378441191&testMode=false
16.94216 0fdc: Info: RobloxIDEDoc::open - start
20.18507 0fdc: Info: 	Locking DataModel
21.82727 0fdc: Info: 	Initializing Ogre
21.82727 0fdc: Info: 	Initializing View
21.88128 0fdc: Info: 	Initializing Explorer
21.91829 0fdc: Info: 	Loading File : 
22.20432 0fdc: Info: 	Loading Plugins
25.71427 0fdc: Error: Plugin_208879363.Stravant_GapFill:690: attempt to perform arithmetic on field '1' (a nil value)
25.71427 0fdc: Info: Stack Begin
25.71626 0fdc: Info: Script 'Plugin_208879363.Stravant_GapFill', Line 690 - local MakeModeGui
25.71727 0fdc: Info: Script 'Plugin_208879363.Stravant_GapFill', Line 823
25.71727 0fdc: Info: Stack End
25.74627 0fdc: Error: Plugin_165687726.GapFill:693: attempt to perform arithmetic on field '1' (a nil value)
25.74727 0fdc: Info: Stack Begin
25.74827 0fdc: Info: Script 'Plugin_165687726.GapFill', Line 693 - local MakeModeGui
25.74827 0fdc: Info: Script 'Plugin_165687726.GapFill', Line 826
25.74927 0fdc: Info: Stack End
25.75927 0fdc: Loaded Plugin: Triangle-Tool [Node Editor] by //INSPARE
27.02544 0fdc: Info: 	Open Success
27.03344 0fdc: Info: RobloxIDEDoc::open - end
31.98806 0fdc: D3D11 Adapter: Intel(R) G45/G43 Express Chipset
31.98806 0fdc: D3D11 Adapter: Vendor 8086 Device 2e22 VRAM 64 RAM 1631
32.84818 0fdc: Video memory size: 67108864
34.85443 0fdc: Loaded shaders from pack d3d10
34.85443 0fdc: Compiled 148 shaders in 2007 ms
34.87043 0fdc: Loaded 16 fonts in 8 ms
34.87343 0fdc: Info: 		RobloxViewStudio::RobloxViewStudio - start
34.87343 0fdc: Info: 			Marshaller
34.87443 0fdc: Info: 			BindToWorkspace
35.15448 0fdc: Info: 			RenderJobCyclic
35.22449 0fdc: Info: 			WrapMouseJob
35.22449 0fdc: Info: 			ConfigureStats
35.45950 0fdc: Info: 		RobloxView::RobloxView - end
35.47950 0fdc: Info: RobloxIDEDoc::activate - start
35.77504 0fdc: Info: RobloxMainWindow::RobloxMainWindow - end
35.77504 0fdc: Info: 

Command line:
C:\Users\anna\AppData\Local\Roblox\Versions\version-64ead513c100423c\RobloxStudioBeta.exe -browser -startEvent www.roblox.com/robloxQTStudioStartedEvent -url https://www.roblox.com/Login/Negotiate.ashx -ticket 12A66E48AAF8B1105CB6290F7DCE19F9649CD2F347D649C76DD38BEC962334274F5AC3A7E9C2F236F5356791D98C3B36E34485864880CDBB900498373167CCDE4A41D949362AF4DA13A55B6218926D0CA110211D54F4E7440DC2AEF86035B6DA8C7EDDADCB1568B7CFBE02D0587EAD03FB08F358 -script https://assetgame.roblox.com/game/edit.ashx?placeId=908690723&upload=908690723&universeId=378441191&testMode=false -readyEvent RBX--1843935299-34093-19756-16613417374181245113221 -avatar -browserTrackerId 9680068821


36.17408 03f0: Info: DataModel Loading https://assetgame.roblox.com/Asset/?id=908690723
310.70148 0fdc: Info: RobloxIDEDoc::saveAs - start
310.73248 0fdc: TlPOU's Place Number: 305 was auto-saved
310.73450 0fdc: Info: RobloxIDEDoc::saveAs - end
606.42993 0fdc: Info: Reloading rbxgameasset://Images/awg texture
608.53632 0fdc: Info: RobloxIDEDoc::saveAs - start
608.54730 0fdc: TlPOU's Place Number: 305 was auto-saved
608.54834 0fdc: Info: RobloxIDEDoc::saveAs - end
619.75323 1224: Content failed to parse for rbxassetid://919328179 because tag expected after Byte-Order-Mark
621.72949 1348: Content failed to parse for rbxassetid://919328179 because tag expected after Byte-Order-Mark
624.87543 0fdc: Info: RobloxScriptDoc::open - start
624.94843 0fdc: Info: RobloxScriptDoc::activate - start
630.79523 0fdc: Info: RobloxIDEDoc::activate - start
633.94958 0fdc: Info: RobloxIDEDoc::saveAs - start
633.97058 0fdc: TlPOU's Place Number: 305 was auto-saved
633.97357 0fdc: Info: RobloxIDEDoc::saveAs - end
651.35925 0fdc: Info: RobloxIDEDoc::saveAs - start
651.37030 0fdc: TlPOU's Place Number: 305 was auto-saved
651.37225 0fdc: Info: RobloxIDEDoc::saveAs - end
664.19043 0fdc: Info: RobloxMainWindow::closeEvent
665.82013 0fdc: Info: Successfully published - TlPOU's Place Number: 305
665.82813 0fdc: Info: RobloxIDEDoc::doClose - start
665.94214 0fdc: Info: RobloxIDEDoc::doClose - end
666.24719 0fdc: Info: RobloxMainWindow::~RobloxMainWindow_

**Comment by zeux** [comment]
Yeah, your GPU is only supporting DirectX 10, but not DirectX 11 - the prototype currently requires DirectX 11.

**Comment by TlPOU** [comment]
Oh. Is there a specific kind of way to get DirectX 11 or it only depends on what kind of computer you have?

**Comment by TlPOU** [comment]
Oh. Because like, I have DirectX 11. But is the prototype gonna be functional for DirectX 10 in the upcoming ROBLOX updates or?[![Screenshot from Gyazo](https://gyazo.com/ff340ec725a8315e281a349bd18efb70/raw)](https://gyazo.com/ff340ec725a8315e281a349bd18efb70)

**Comment by DoctorPurpleSwag** [comment]
**Here is my crash report:**
0.03000 18bc: CrashReporter Start
0.03000 1e70: WatcherThread Started
0.03100 18bc: Initializing CrashEvent request, url: https://data.roblox.com/Error/Dmp.ashx?filename=C%3A%5CUsers%5CBruno%5CAppData%5CLocal%5CRoblox%5Clogs%5Clog%5F36992%200%2C%200%2C%200%2C%20138616%2ERobloxStudio%2Ecrashevent
0.03100 18bc: Info: RobloxMainWindow::RobloxMainWindow - start
0.91407 18bc: StudioABTests using browserTrackerId 9495798760
2.91253 18bc: setAssetFolder C:/Users/Bruno/AppData/Local/Temp/Rar$EXa0.776/future-is-bright-v1/content
3.32179 18bc: Info: RobloxMainWindow::createAndShowIDEDocFromScript 
3.32279 18bc: Info: createRobloxDoc
3.33379 18bc: Info: RobloxMainWindow::RobloxMainWindow - end
3.33379 18bc: Info: 

Command line:
C:\Users\Bruno\AppData\Local\Temp\Rar$EXa0.776\future-is-bright-v1\RobloxStudioBeta.exe


36.22157 18bc: Info: RobloxMainWindow::createAndShowIDEDocFromScript https://assetgame.roblox.com/Game/edit.ashx?PlaceID=933280853&upload=933280853&testmode=false
38.66893 18bc: Info: RobloxIDEDoc::open - start
38.70796 18bc: Info: 	Locking DataModel
38.73398 18bc: Info: 	Initializing Ogre
38.73398 18bc: Info: 	Initializing View
38.73799 18bc: Info: 	Initializing Explorer
38.75600 18bc: Info: 	Loading File : 
38.83611 18bc: Info: 	Loading Plugins
39.24789 18bc: Info: 	Open Success
39.25189 18bc: Info: RobloxIDEDoc::open - end
40.14979 18bc: GL Renderer: GeForce GTX 750 Ti/PCIe/SSE2
40.15079 18bc: GL Version: 4.5.0 NVIDIA 378.49
40.15079 18bc: GL Vendor: NVIDIA Corporation
40.15079 18bc: GLSL version: 4.50 NVIDIA
40.15079 18bc: Ext: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility
40.15079 18bc: Ext: GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage
40.15079 18bc: Ext: GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage
40.15079 18bc: Ext: GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer
40.15079 18bc: Ext: GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control
40.15079 18bc: Ext: GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced
40.15079 18bc: Ext: GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport
40.15079 18bc: Ext: GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object
40.15079 18bc: Ext: GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5
40.15079 18bc: Ext: GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters
40.15079 18bc: Ext: GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment
40.15079 18bc: Ext: GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query
40.15079 18bc: Ext: GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters
40.15079 18bc: Ext: GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior
40.15079 18bc: Ext: GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects
40.15079 18bc: Ext: GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock
40.15079 18bc: Ext: GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects
40.15079 18bc: Ext: GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod
40.15079 18bc: Ext: GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow
40.15079 18bc: Ext: GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier
40.15079 18bc: Ext: GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression
40.15079 18bc: Ext: GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add
40.15079 18bc: Ext: GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge
40.15079 18bc: Ext: GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod
40.15079 18bc: Ext: GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample
40.15079 18bc: Ext: GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced
40.15079 18bc: Ext: GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object
40.15079 18bc: Ext: GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev
40.15079 18bc: Ext: GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once
40.15079 18bc: Ext: GL_EXTX_framebuffer_mixed_formats GL_EXT_Cg_shader GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate
40.15079 18bc: Ext: GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_depth_bounds_test GL_EXT_direct_state_access
40.15079 18bc: Ext: GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample
40.15079 18bc: Ext: GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters
40.15179 18bc: Ext: GL_EXT_gpu_shader4 GL_EXT_import_sync_object GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels
40.15179 18bc: Ext: GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color
40.15179 18bc: Ext: GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store
40.15179 18bc: Ext: GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array
40.15179 18bc: Ext: GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc
40.15179 18bc: Ext: GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic
40.15179 18bc: Ext: GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_sRGB
40.15179 18bc: Ext: GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2
40.15179 18bc: Ext: GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat
40.15179 18bc: Ext: GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error
40.15179 18bc: Ext: GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KTX_buffer_region GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_NVX_multigpu_info
40.15179 18bc: Ext: GL_NVX_nvenc_interop GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect
40.15179 18bc: Ext: GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent
40.15179 18bc: Ext: GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image
40.15179 18bc: Ext: GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_explicit_multisample GL_NV_fence GL_NV_float_buffer
40.15179 18bc: Ext: GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program2 GL_NV_fragment_program_option GL_NV_framebuffer_multisample_coverage
40.15179 18bc: Ext: GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64
40.15179 18bc: Ext: GL_NV_gpu_shader5 GL_NV_half_float GL_NV_internalformat_sample_query GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint
40.15179 18bc: Ext: GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering
40.15179 18bc: Ext: GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters
40.15179 18bc: Ext: GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_thread_group
40.15179 18bc: Ext: GL_NV_shader_thread_shuffle GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4
40.15179 18bc: Ext: GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback
40.15179 18bc: Ext: GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit
40.15179 18bc: Ext: GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option
40.15179 18bc: Ext: GL_NV_vertex_program3 GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
40.15179 18bc: Ext: GL_WIN_swap_hint WGL_EXT_swap_control
40.15179 18bc: Caps: ThreadSafe 0 Framebuffer 1 Shaders 1 Compute 0 Instancing 0
40.15179 18bc: Caps: Framebuffer: MRT 8 MSAA 32 Stencil 0 Depth24 1 DepthFloat 1
40.15179 18bc: Caps: Texture: DXT 1 PVR 0 ETC1 0 ETC2 0 Half 1
40.15179 18bc: Caps: Texture: 3D 1 Array 1 Depth 1 MSAA 1
40.15179 18bc: Caps: Texture: NPOT 1 PartialMips 1
40.15179 18bc: Caps: Texture: Size 16384 Units 16
40.15179 18bc: Caps: 32bIdx 1
40.15179 18bc: Caps: ColorBGR 0 HalfPixelOffset 0 RTFlip 1 MinusOneToOneDepth 1
40.15179 18bc: Caps: Retina 0
40.15179 18bc: Caps: GL3 1
40.15179 18bc: Caps: VAO 1 TexStorage 1 MapBuffer 1 MapBufferRange 1
40.15179 18bc: Caps: TimerQuery 1 Sync 1
40.80980 18bc: Video memory size: 2115698688
40.81080 18bc: Warning: Mode 4 failed: "Error opening shader pack glsl3 (C:\Users\Bruno\AppData\Local\Temp\Rar$EXa0.776\future-is-bright-v1\content/../shaders/shaders_glsl3.pack)"
40.81080 18bc: Info: 	Exception : Your graphics drivers seem to be too old for Roblox to use.

Visit http://www.roblox.com/drivers for info on how to perform a driver upgrade.
40.81080 18bc: Error: Your graphics drivers seem to be too old for Roblox to use.

Visit http://www.roblox.com/drivers for info on how to perform a driver upgrade.
40.81280 18bc: Info: RobloxIDEDoc::activate - start
40.86186 0e7c: Info: DataModel Loading https://assetgame.roblox.com/Asset/?id=933280853
45.00106 18bc: Info: RobloxIDEDoc::activate - start
49.59997 18bc: Info: RobloxIDEDoc::activate - start
53.13564 18bc: Info: RobloxMainWindow::closeEvent
55.47774 18bc: Info: RobloxIDEDoc::doClose - start
55.52280 18bc: Info: RobloxIDEDoc::doClose - end
55.60295 18bc: Info: RobloxMainWindow::~RobloxMainWindow

**Comment by DoctorPurpleSwag** [comment]
Turns out i just had OpenGL graphics mode now that i switched to Direct3D11 it works fine.

**Comment by TlPOU** [comment]
Oh. How do i do that? Is it like, some stuff in ROBLOX Studio settings or

**Comment by zeux** [comment]
There were a few reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download from https://github.com/Roblox/future-is-bright/releases should either work or clearly indicate that your system is currently incompatible.
